// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksvNyqGt_wtTkNyOvO4kRVr_3WVSm6yo',
    appId: '1:572278114585:web:a36c42ee75f2af7a449d88',
    messagingSenderId: '572278114585',
    projectId: 'chat-app-3e15d',
    authDomain: 'chat-app-3e15d.firebaseapp.com',
    storageBucket: 'chat-app-3e15d.appspot.com',
    measurementId: 'G-0EQ4BHZQEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbU5sFsSjxCo1blwI9PA8VE0UeDFkF-RI',
    appId: '1:572278114585:android:4dd67d915d546f17449d88',
    messagingSenderId: '572278114585',
    projectId: 'chat-app-3e15d',
    storageBucket: 'chat-app-3e15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxnjrX4d6-GILLrclutrtYBJpUPUoYfs',
    appId: '1:572278114585:ios:f540def38402ac09449d88',
    messagingSenderId: '572278114585',
    projectId: 'chat-app-3e15d',
    storageBucket: 'chat-app-3e15d.appspot.com',
    iosBundleId: 'com.mridul.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxnjrX4d6-GILLrclutrtYBJpUPUoYfs',
    appId: '1:572278114585:ios:f540def38402ac09449d88',
    messagingSenderId: '572278114585',
    projectId: 'chat-app-3e15d',
    storageBucket: 'chat-app-3e15d.appspot.com',
    iosBundleId: 'com.mridul.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksvNyqGt_wtTkNyOvO4kRVr_3WVSm6yo',
    appId: '1:572278114585:web:5119bc8302485813449d88',
    messagingSenderId: '572278114585',
    projectId: 'chat-app-3e15d',
    authDomain: 'chat-app-3e15d.firebaseapp.com',
    storageBucket: 'chat-app-3e15d.appspot.com',
    measurementId: 'G-LS4X5DJL86',
  );
}
